language: node_js
node_js:
- "0.10"
- "4.1"
- "5.5"
before_script: npm install coveralls
script: node_modules/.bin/istanbul cover --report lcovonly node_modules/mocha/bin/_mocha
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- rm -rf ./coverage
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
